#EXTRACFLAGS = -DDEBUG_SYSTEMC -Wl,-rpath,/zwork/sysc/libsysc/lib-linux64
EXTRACFLAGS = -DDEBUG_SYSTEMC
EXTRA_LIBS =
MODULE = run
SRCS = $(wildcard *.cpp)

OBJS = $(SRCS:.cpp=.o)

include ../Makefile.defs
